### PR TITLE
mixin option

### PR DESCRIPTION
**Pull request by developerdayo**
boolean option called 'outputMixins' which generates a _sassvg-mixins.scss file in order to preserve the original colors of multicolored mixins

### CODE REVIEW

**Comment by MattDiMu** [comment]
Thx for your pull request.

What are the use cases for adding the original SVG-files in a _sassvg_mixins.scss file? If no transformations are made, can't they simply be included directly?

**Comment by developerdayo** [comment]
Sure.

I'm requesting this feature because the team I'm apart of builds solutions on CMS and due to the nature of developing for CMS, we are using css to implement SVG's 95% of the time. So adding the svg directly is not something we're doing often.

I didn't notice the 'no-sassvg' rule :) . I see that it works–nice. My only qualm is its a minor annoyance to have to add the class on the proper node for it to bypass adding the variables though adding the sassvg-mixins file could be a perceived annoyance as well. Maybe added no-sassvg to the file name would be more intuitive. What do you think? I'll ask my team to get their feedback tomorrow.

Thank you for responding.

**Comment by MattDiMu** [comment]
True, having to adapt the Source-File isn't that nice, but on the other hand it allows the developer to only ignore the secondary (or tertiary) color, making the primary color still style-able as well as adding further filters to the SVG. So in the long run (especially if this SVG is reused in other themes/sites) this feels like the better option. 

Furthermore having the SVG still under control of sassvg, enables the developer to add additional filters to the SVG as well, even if the color shouldn't change. e.g. opacity, blurring, etc.: https://caniuse.com/#feat=svg-filters

**Comment by developerdayo** [comment]
@MattDiMu what do you think about having the option to bypass adding the sass variables if '-nosassvg' is added to the svg file name (ex: telephone-nosassvg.svg) as well as retain the no-sassvg class that you currently have? spoke with my team and we all agree that perhaps the mixin route was not the best answer but the no-sassvg class is also cumbersome and we are pretty much never wanting to control each path of an svg.

if you are open to this, i can submit another pull request with that functionality.

**Comment by MattDiMu** [comment]
@developerdayo Thx for your teams feedback. Option 1 seems reasonable to me. So files with the "-nosassvg" should simply serve the original SVG without any variables/replacements.

I'm willing to implement this feature, but cannot guarantee any deadline atm. So yes, another pull request would be highly appreciated!

**Comment by PrinceCharles23** [comment]
seems like this promised PR never came...? i actually would prefer to keep file names as is and suggest to configure this in gulp

**Pull request closed without merging**
